Feature/implement rviz in tachimawari
ichiro-its/tachimawari pull request #52
Opened 2023-01-21 07:57 UTC by marfanr

## Jira Link: 

## Description

Describe problems, if any, clearly and concisely.
Describe any changes that have been made in this pull request.

## Type of Change

- [ ] Bugfix
- [ ] Enhancement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause the existing functionality to not work as expected)

## How Has This Been Tested?

- [ ] New unit tests added.
- [ ] Manual tested.

## Checklist:

- [ ] Using Branch Name Convention
    - `feature/JIRA-ID-SHORT-DESCRIPTION` if has a JIRA ticket
    - `enhancement/SHORT-DESCRIPTION` if has/has no JIRA ticket and contain enhancement
    - `hotfix/SHORT-DESCRIPTION` if the change doesn't need to be tested (urgent)
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have made the documentation for the corresponding changes.

2023-02-16 16:53 UTC, Alffaza requested changes

2023-02-16 16:53 UTC, Alffaza commented on src/tachimawari/node/rviz_client_node.cpp
> +double RvizClientNode::val2deg(int val)
shouldn't the function name be `val2rad`?

2023-02-16 16:53 UTC, Alffaza commented on src/tachimawari/node/rviz_client_node.cpp
> +    geometry_msgs::msg::TransformStamped t;
I suggest giving this variable a more descriptive name like `world_transform`

2023-02-16 16:53 UTC, Alffaza commented on src/tachimawari/node/rviz_client_node.cpp
> +    sensor_msgs::msg::JointState js;
i think `joint_state_msg` would be a better variable name

2023-02-16 16:53 UTC, Alffaza commented on include/tachimawari/node/rviz_server_node.hpp
> +  std::shared_ptr<tachimawari::control::ControlManager> controlmanager;
please rename these variables to make them easier to read. `joint_manager`, `control_manager`

2023-02-17 03:20 UTC, threeal requested changes

2023-02-17 03:20 UTC, threeal commented on src/rviz_client_main.cpp
> +// Copyright (c) 2021 Ichiro ITS
bro it's 2023 lol 🤣

2023-02-17 03:20 UTC, threeal commented on src/tachimawari/node/rviz_client_node.cpp
> +      for (int i = 0; i < 20; i++) {
please `++i` over `i++` 🙏

2023-02-17 03:20 UTC, threeal commented on src/tachimawari/node/rviz_client_node.cpp
> +    register_joint(js, "body_to_robot", (3.14 / 180) * 0);
what's the point of `(3.14 / 180) * 0` 🙈

2023-02-17 03:20 UTC, threeal commented on include/tachimawari/node/rviz_client_node.hpp
> +  void register_joint(sensor_msgs::msg::JointState & js, std::string name, double pos);
i suggest to pass the `std::string` as a const ref (`const std::string&`).

2023-02-17 03:20 UTC, threeal commented on include/tachimawari/node/rviz_client_node.hpp
> +  RvizClientNode(rclcpp::Node::SharedPtr node, musen::Client client);
I suggest to use const ref in here too. Even if there's a shared pointer here.

2023-02-17 03:20 UTC, threeal commented on src/tachimawari/node/rviz_server_node.cpp
> +  for (auto joint : joints) {
i suggest to use `const auto&` in `joint`

2023-02-17 03:20 UTC, threeal commented on src/tachimawari/node/rviz_client_node.cpp
> +      for (int i = 0; i < 20; i++) {
and please check the other lines too

2023-02-17 14:03 UTC, Alffaza approved these changes

2023-02-18 12:06 UTC, threeal requested changes

2023-02-18 12:06 UTC, threeal commented on include/tachimawari/node/rviz_client_node.hpp
> +  RvizClientNode(const rclcpp::Node::SharedPtr node, const musen::Client client);
It should be constant reference instead of just constant
```
const Person p1; // constant
const Person& p2; // constant reference
```

2023-02-18 12:07 UTC, threeal commented on include/tachimawari/node/rviz_client_node.hpp
> +  RvizClientNode(const rclcpp::Node::SharedPtr node, const musen::Client client);
and please check other lines

2023-02-22 02:34 UTC, threeal approved these changes

2023-03-07 10:22 UTC, merged