[Sprint 22/23 / PI-412] - [Feature] Implement TF2 Tree
ichiro-its/tachimawari pull request #61
Opened 2024-05-25 20:04 UTC by borednuna

## Jira Link: https://ichiro-its.atlassian.net/browse/PD-412

## Description

Implement TF2 to represent the robot's physical movements as transform frames and publish them.

## Type of Change

- [ ] Bugfix
- [ ] Enhancement
- [x] New feature
- [ ] Breaking change (fix or feature that would cause the existing functionality to not work as expected)

## How Has This Been Tested?

- [ ] New unit tests added.
- [x] Manual tested.

## Checklist:

- [x] Using Branch Name Convention
    - `feature/JIRA-ID-SHORT-DESCRIPTION` if has a JIRA ticket
    - `enhancement/SHORT-DESCRIPTION` if has/has no JIRA ticket and contain enhancement
    - `hotfix/SHORT-DESCRIPTION` if the change doesn't need to be tested (urgent)
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have made the documentation for the corresponding changes.

2024-05-29 13:17 UTC, FaaizHaikal commented on include/tachimawari/joint/tf2/frame.hpp
> +
No need to assign int values in enum

2024-05-29 13:17 UTC, FaaizHaikal commented on include/tachimawari/joint/tf2/frame_id.hpp
> +  };
ditto.

2024-05-29 13:17 UTC, FaaizHaikal commented on include/tachimawari/node/tachimawari_node.hpp
> +  void run_joint_manager(std::string path);
```suggestion
  void run_joint_manager(const std::string & path);
```

2024-05-29 13:17 UTC, FaaizHaikal commented on include/tachimawari/joint/tf2/tf2_manager.hpp
> +  bool load_configuration(std::string path);
```suggestion
  bool load_configuration(const std::string & path);
```

2024-05-29 13:17 UTC, FaaizHaikal commented on src/tachimawari/joint/tf2/tf2_manager.cpp
> +  }
Better to throw the exception instead of letting the program running with unknown behavior.
```suggestion
    } catch (nlohmann::json::parse_error & ex) {
      std::cerr << "parse error at byte " << ex.byte << std::endl;
      throw ex;
    }
  }
```

2024-05-29 13:17 UTC, FaaizHaikal commented on include/tachimawari/joint/tf2/tf2_manager.hpp
> +  std::string config_path;
cmiiw, i don't see this variable ever used

2024-05-29 13:22 UTC, FaaizHaikal commented on include/tachimawari/node/tachimawari_node.hpp
> +  rclcpp::TimerBase::SharedPtr node_timer_tf;
cmiiw, this also unused

2024-05-29 15:39 UTC, FaaizHaikal commented on include/tachimawari/joint/node/joint_node.hpp
> +    rclcpp::Node::SharedPtr node, std::shared_ptr<JointManager> joint_manager, std::string path);
```suggestion
  JointNode(
    rclcpp::Node::SharedPtr node, std::shared_ptr<JointManager> joint_manager, const std::string & path);
```

2024-06-06 19:41 UTC, FaaizHaikal commented on src/tachimawari/joint/tf2/frame.cpp
> +void Frame::update_quaternion(keisan::Angle<double> imu_yaw)
ditto

2024-06-06 19:41 UTC, FaaizHaikal commented on src/tachimawari/joint/tf2/frame.cpp
> +geometry_msgs::msg::TransformStamped Frame::get_transform_stamped(rclcpp::Time time_stamp)
If object is not modified in the function, can pass as const reference instead.

2024-06-06 19:41 UTC, FaaizHaikal commented on src/tachimawari/joint/tf2/frame.cpp
> +void Frame::update_quaternion(std::vector<Joint> current_joints)
ditto

2024-06-06 19:41 UTC, FaaizHaikal commented on src/tachimawari/joint/tf2/frame.cpp
> +double Frame::get_joint_angle(uint8_t quaternion_axis, std::vector<Joint> current_joints)
ditto

2024-06-06 19:41 UTC, FaaizHaikal commented on src/tachimawari/joint/tf2/tf2_manager.cpp
> +void Tf2Manager::update(std::vector<Joint> current_joints, keisan::Angle<double> imu_yaw)
ditto

2024-06-07 02:56 UTC, JayantiTA requested changes

2024-06-07 02:56 UTC, JayantiTA commented on include/tachimawari/joint/node/joint_node.hpp
> +#include <tf2_ros/buffer.h>
library order, check another files too

2024-06-08 08:00 UTC, FaaizHaikal approved these changes

2024-06-08 08:18 UTC, JayantiTA approved these changes

2024-06-15 13:29 UTC, merged